version: '3'

services:
  eureka-server:
    image: eureka-server:latest
    container_name: eureka_server_container
    build: ./nwt-eureka-server
    ports:
      - 8761:8761
    networks:
      - app

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: vhost
    networks:
      - app

  movies:
    build: ./nwt-cinema-movies
    container_name: movies_container
    depends_on: 
      - database
      - eureka-server
      - rabbitmq
    ports:
      - 8030:8030
    networks:
      - app

  projections:
    build: ./nwt-cinema-projections
    container_name: projections_container
    depends_on:
      - database
      - eureka-server
      - rabbitmq
    ports:
      - 8040:8040
    networks:
      - app

  reservations:
    build: ./nwt-cinema-reservations
    container_name: reservations_container
    links:
      - eureka-server
    depends_on:
      - database
      - eureka-server
      - rabbitmq
    ports:
      - 8050:8050
    networks:
      - app

  database:
    restart: always
    image: sameersbn/postgresql
    container_name: pg_container
    volumes:
       - /srv/docker/postgresql:/var/lib/postgresql
    environment:
       - DB_NAME=nwt-cinema-movies,nwt-cinema-projections,nwt-cinema-reservations
       - DB_USER=nwt
       - DB_PASS=nwt
    ports:
       - 5433:5432
    networks:
       - app

networks:
  app:
    driver: bridge

 
