version: '3'

services:
  movies:
    build: ./nwt-cinema-movies
    container_name: movies_container
    depends_on: 
       - database
       - rabbit1
    ports:
       - 8030:8030
    networks:
       - app

  projections:
    build: ./nwt-cinema-projections
    container_name: projections_container
    depends_on:
       - database
    ports:
       - 8040:8040
    networks:
       - app

  reservations:
    build: ./nwt-cinema-reservations
    container_name: reservations_container
    depends_on:
       - database
    ports:
       - 8050:8050
    networks:
       - app

  database:
    image: sameersbn/postgresql
    container_name: pg_container
    volumes:
       - /srv/docker/postgresql:/var/lib/postgresql
    environment:
       - DB_NAME=nwt-cinema-movies,nwt-cinema-projections,nwt-cinema-reservations
       - DB_USER=nwt
       - DB_PASS=nwt
      # - PGDATA=/var/lib/postgresql/data/pgdata
      # - PGPORT=5432
    ports:
       - 5433:5432
    networks:
       - app

  rabbit1:
    image: "rabbitmq:latest"
    hostname: "rabbit1"
    environment:
       - RABBITMQ_ERLANG_COOKIE=secret_cookie
    ports:
       - "15672:15672"
       - "5672:5672"
    labels:
       NAME: "rabbitmq1"
    volumes:
       - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    networks:
       - app

#volumes:
#  psql_data: 

networks:
  app:

 
