version: '3'

services:
  eureka-server:
    image: eureka-server:latest
    container_name: eureka_server_container
    build: ./nwt-eureka-server
    ports:
      - 8761:8761
    network_mode: bridge
    # networks:
    #   - app

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    network_mode: bridge

  movies:
    build: ./nwt-cinema-movies
    container_name: movies_container
    environment: 
      SPRING_RABBITMQ_HOST: 172.17.0.1
    depends_on: 
      - database
      - eureka-server
      - rabbitmq
    ports:
      - 8030:8030
    network_mode: bridge

  projections:
    build: ./nwt-cinema-projections
    container_name: projections_container
    environment:
      SPRING_RABBITMQ_HOST: 172.17.0.1
    depends_on:
      - database
      - eureka-server
      - rabbitmq
    ports:
      - 8040:8040
    network_mode: bridge

  reservations:
    build: ./nwt-cinema-reservations
    container_name: reservations_container
    environment:
      SPRING_RABBITMQ_HOST: 172.17.0.1
    depends_on:
      - database
      - eureka-server
      - rabbitmq
    ports:
      - 8050:8050
    network_mode: bridge

  database:
    image: sameersbn/postgresql
    container_name: pg_container
    restart: always
    volumes:
       - /srv/docker/postgresql:/var/lib/postgresql
    environment:
       - DB_NAME=nwt-cinema-movies,nwt-cinema-projections,nwt-cinema-reservations
       - DB_USER=nwt
       - DB_PASS=nwt
    ports:
       - 5433:5432
    network_mode: bridge

  gateway:
    build: ./nwt-api-gateway
    image: zuul-server:latest
    container_name: api_gateway_container
    environment:
      - EUREKA_HOST=eureka-server
    depends_on:
      - eureka-server
    links: 
      - eureka-server
    ports:
      - 8080:8080
    network_mode: bridge

 
